name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.13-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y make curl
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install project
        run: make install

      - name: Run tests
        run: make test
